name: AutoTest for Microblog

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.10, 3.11]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt
      continue-on-error: true

    - name: Set environment variables
      run: |
        echo "FLASK_APP=microblog.py" >> $GITHUB_ENV
        echo "FLASK_ENV=development" >> $GITHUB_ENV
      continue-on-error: true

    - name: Initialize database
      run: |
        flask db upgrade
      continue-on-error: true
      
    - name: Start server
      run: |
        flask run
      continue-on-error: true

    - name: Run tests
      run: |
        pytest tests.py
      continue-on-error: true

